//
//  FavoriteMusicView.m
//  KarenMok
//
//  Created by 柴勇峰 on 6/14/16.
//  Copyright © 2016 BraveMatch. All rights reserved.
//

#import "ReactView.h"
#import <React/RCTRootView.h>

@implementation ReactView

- (instancetype)init
{
    return [self initWithFrame:CGRectZero];
}

- (instancetype)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    
    if (self) {
        
        [self commonInit];
    }
    
    return self;
}

- (void)commonInit
{
    NSURL *jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle?platform=ios"];
    // For production use, this `NSURL` could instead point to a pre-bundled file on disk:
    //
    //   NSURL *jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
    //
    // generated by "Bundle React Native code and images" build step.
    //
    //   curl http://localhost:8081/index.ios.bundle -o main.jsbundle
    RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation moduleName:@"AwesomeProject" initialProperties:nil launchOptions:nil];
    
    [self addSubview:rootView];
    rootView.frame = self.bounds;
}

- (void)awakeFromNib
{
    [self commonInit];
}

@end
